checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint

  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_{step}"
  auto_insert_metric_name: false
  save_last: true

  monitor: "val/RetriAcc"
  mode: "max"
  save_top_k: 2

  verbose: true
